# Generated by Django 5.2.3 on 2025-07-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_lead_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ('name',)},
        ),
    ]
